### ISSUE TITLE
Selecting the Schema in Faber on the "CredentialsSchema" screen generates error

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-acapy-controllers#80]
When I select the Schema in the drop down, the following error appears on the logs:

```
faber-controller_1  | fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
faber-controller_1  |       Unhandled exception in circuit 'vZkbr75ICYHFcMWpnASVzOnxGz9te7Vvwuxm7Ze1Zfk'.
faber-controller_1  | System.NullReferenceException: Object reference not set to an instance of an object.
faber-controller_1  |    at FaberController.Schema.Components.Schema.OnSelectSchema(ChangeEventArgs e) in /app/FaberController/Schema/Components/Schema.razor:line 46
faber-controller_1  |    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
faber-controller_1  |    at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
faber-controller_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
faber-controller_1  | --- End of stack trace from previous location where exception was thrown ---
faber-controller_1  |    at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

And on the screen:

`An error has occurred. This application may no longer respond until reloaded. [Reload](http://192.168.50.213:9021/)`

**Comment by amanji** [comment]
Was this fixed with #78?
